name: Build Jekyll site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install Jekyll
        run: gem install jekyll bundler
      - name: Build with Jekyll
        run: bundle exec jekyll build
